using PhotoSweep.Core.Hashing;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using Xunit.Abstractions;

namespace PhotoSweep.Tests.Hashing;

// End-to-end on real files in TestData/Photos (generated by tools/GenerateTestImages.cs).
//
// The bounds below are SANITY bounds, deliberately loose and NOT tuned to the current output. They only
// check that the hashes behave roughly as designed. The real "is this a duplicate?" thresholds get chosen
// later from an evaluation set.
//   - Unrelated images give roughly random bits: expected distance ≈ 32 of 64, standard deviation ≈ 4.
//     20 is about 3σ below that, so an unrelated pair landing under 20 would point to a real bug.
//   - SameMaxDistance = 10 leaves a wide gap to 20, so "same" and "different" can't be confused.
//     The edits tested here (resize, recompress, PNG, EXIF rotation) should come in well under it.
//     A variant reaching 10 means something is wrong, e.g. orientation not applied or a resize artefact.
public class FingerprintRobustnessTests(ITestOutputHelper output)
{
    private const int SameMaxDistance = 10;
    private const int DifferentMinDistance = 20;

    private static readonly string PhotoDir = Path.Combine(AppContext.BaseDirectory, "TestData", "Photos");

    public static TheoryData<string, string> Variants()
    {
        var data = new TheoryData<string, string>();
        foreach (var name in new[] { "astronaut", "chelsea", "coffee" })
        foreach (var variant in new[] { "_half.jpg", "_q50.jpg", ".png", "_exif6.jpg", "_harsh.jpg" })
            data.Add(name, name + variant);
        return data;
    }

    // The mild edits above all hash to distance 0, which would also happen if the tolerance were never
    // exercised. The harsh variant (quarter size + brighter + JPEG q20) must actually move some bits,
    // proving the "same" test above is checking a real non-zero distance against the limit.
    [Fact]
    public void Harsh_variants_move_at_least_one_bit()
    {
        var total = 0;
        foreach (var name in new[] { "astronaut", "chelsea", "coffee" })
        {
            var original = Fingerprint(name + ".jpg");
            var harsh = Fingerprint(name + "_harsh.jpg");
            total += Hamming.Distance(original.PHash, harsh.PHash) + Hamming.Distance(original.DHash, harsh.DHash);
        }

        Assert.True(total > 0, "harsh variants hashed identically to their originals; the test images are too gentle");
    }

    [Theory]
    [MemberData(nameof(Variants))]
    public void Same_photo_after_edit_is_close(string name, string variantFile)
    {
        var original = Fingerprint(name + ".jpg");
        var variant = Fingerprint(variantFile);

        var p = Hamming.Distance(original.PHash, variant.PHash);
        var d = Hamming.Distance(original.DHash, variant.DHash);
        output.WriteLine($"{variantFile}: pHash {p}, dHash {d}");

        Assert.True(p <= SameMaxDistance, $"pHash distance {p} > {SameMaxDistance}");
        Assert.True(d <= SameMaxDistance, $"dHash distance {d} > {SameMaxDistance}");
    }

    [Theory]
    [InlineData("astronaut", "chelsea")]
    [InlineData("astronaut", "coffee")]
    [InlineData("chelsea", "coffee")]
    public void Different_photos_are_far_apart(string a, string b)
    {
        var fa = Fingerprint(a + ".jpg");
        var fb = Fingerprint(b + ".jpg");

        var p = Hamming.Distance(fa.PHash, fb.PHash);
        var d = Hamming.Distance(fa.DHash, fb.DHash);
        output.WriteLine($"{a} vs {b}: pHash {p}, dHash {d}");

        Assert.True(p >= DifferentMinDistance, $"pHash distance {p} < {DifferentMinDistance}");
        Assert.True(d >= DifferentMinDistance, $"dHash distance {d} < {DifferentMinDistance}");
    }

    // Control: proves the EXIF test above passes *because* of AutoOrient, not by luck. Hash the
    // sideways-stored pixels as-is (Image.Load does not auto-orient) and they should look like a different photo.
    [Theory]
    [InlineData("astronaut")]
    [InlineData("chelsea")]
    [InlineData("coffee")]
    public void Exif_rotated_photo_without_auto_orient_is_far_apart(string name)
    {
        var original = Fingerprint(name + ".jpg");
        using var sideways = Image.Load<L8>(Path.Combine(PhotoDir, name + "_exif6.jpg"));
        var raw = Fingerprinter.Compute(sideways);

        var p = Hamming.Distance(original.PHash, raw.PHash);
        var d = Hamming.Distance(original.DHash, raw.DHash);
        output.WriteLine($"{name}_exif6 without AutoOrient: pHash {p}, dHash {d}");

        Assert.True(p >= DifferentMinDistance, $"pHash distance {p} < {DifferentMinDistance}");
        Assert.True(d >= DifferentMinDistance, $"dHash distance {d} < {DifferentMinDistance}");
    }

    [Fact]
    public void Path_and_stream_overloads_agree()
    {
        var path = Path.Combine(PhotoDir, "coffee.jpg");
        using var stream = File.OpenRead(path);

        Assert.Equal(Fingerprinter.Compute(path), Fingerprinter.Compute(stream));
    }

    private static ImageFingerprint Fingerprint(string file) => Fingerprinter.Compute(Path.Combine(PhotoDir, file));
}
